env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  global-require: 0
  max-len:
    - 2
    - 150
  comma-dangle: 0
  no-tabs: 0
  indent:
    - error
    - tab
  function-paren-newline: 0
  implicit-arrow-linebreak: 0
  object-curly-newline: 0
  import/prefer-default-export: 0
  react/react-in-jsx-scope: off
  react/jsx-indent: 0
  react/jsx-indent-props: 0
  react/jsx-one-expression-per-line:
    - 0
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  react/function-component-definition:
    - 0
    - namedComponenets:
        - function-declaration
        - arrow-function
  jsx-quotes:
    - error
    - prefer-single
