env:
    browser: true
    es2021: true
extends:
    - plugin:react/recommended
    - airbnb
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 13
    sourceType: module
plugins:
    - react
rules:
    comma-dangle: 0
    no-tabs: 0
    react/jsx-indent:
        - 2
        - tab
    indent:
        - error
        - tab
    react/react-in-jsx-scope: off
    react/jsx-filename-extension:
        - 1
        - extensions:
              - .js
              - .jsx
    object-curly-newline: 0
    react/function-component-definition:
        - 2
        - namedComponenets: function-declaration
